export const themes = {
  'warm-sand': {
    label: 'Warm Sand',
    bg: '#F5F5F0',
    surface: '#EEEEE8',
    border: '#D8D8D0',
    primary: '#CC785C',
    text: '#1A1A1A',
    muted: '#888888',
  },
  'dark-slate': {
    label: 'Dark Slate',
    bg: '#0F1117',
    surface: '#1A1D27',
    border: '#2A2D3A',
    primary: '#7C8CF8',
    text: '#F0F0F0',
    muted: '#666666',
  },
  forest: {
    label: 'Forest',
    bg: '#F0F4F0',
    surface: '#E4EBE4',
    border: '#C8D4C8',
    primary: '#3D7A5E',
    text: '#1A2A1A',
    muted: '#777777',
  },
  'midnight-blue': {
    label: 'Midnight Blue',
    bg: '#0D1B2A',
    surface: '#1A2E42',
    border: '#243D52',
    primary: '#5DADE2',
    text: '#EAF4FB',
    muted: '#5A7080',
  },
  'paper-white': {
    label: 'Paper White',
    bg: '#FFFFFF',
    surface: '#F5F5F5',
    border: '#E0E0E0',
    primary: '#333333',
    text: '#111111',
    muted: '#888888',
  },
};

export const fontOptions = [
  { value: 'DM Sans',        label: 'DM Sans',        style: "'DM Sans', sans-serif" },
  { value: 'Inter',          label: 'Inter',           style: "'Inter', sans-serif" },
  { value: 'Lato',           label: 'Lato',            style: "'Lato', sans-serif" },
  { value: 'Merriweather',   label: 'Merriweather',    style: "'Merriweather', serif" },
  { value: 'JetBrains Mono', label: 'JetBrains Mono', style: "'JetBrains Mono', monospace" },
];
